import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button, Card, Input } from "../components/ui.jsx";
import { getReceptionistPatientProfiles } from "../../../shared/services/receptionistPatientApi.js";

export default function ReceptionistPatientDataApiPage() {
  const navigate = useNavigate(); const [query, setQuery] = useState(""); const [patients, setPatients] = useState([]); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); try { const result = await getReceptionistPatientProfiles({ search: query, limit: 100 }); setPatients(result.data); setTotal(result.pagination?.total || result.data.length); } catch (requestError) { setError(requestError.message || "Pasien tidak dapat dimuat."); } finally { setLoading(false); } };
  useEffect(() => { const timeout = setTimeout(load, 250); return () => clearTimeout(timeout); }, [query]);
  return <div className="flex flex-col gap-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-[#434655]">Manajemen data pasien</p><h1 className="text-[28px] font-bold">Data Pasien</h1></div><Button onClick={() => navigate("/resepsionis/data-pasien/baru")}>Tambah Pasien</Button></div><Card pad="md"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari nama, email, telepon, atau kota" /><p className="mt-3 text-xs text-[#434655]">{total} pasien terdaftar</p></Card><Card>{error && <p className="m-5 rounded-lg bg-[#fdf1f1] p-3 text-sm text-[#a03d4a]">{error}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[700px]"><thead><tr className="border-b bg-[#f5f5f3]/60 text-left">{["Pasien", "Telepon", "Email", "Kota", "Aksi"].map((label) => <th key={label} className="px-5 py-3 text-xs text-[#434655]">{label}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan="5" className="p-8 text-center text-sm">Memuat pasien…</td></tr> : patients.length === 0 ? <tr><td colSpan="5" className="p-8 text-center text-sm">Tidak ada pasien.</td></tr> : patients.map((patient) => <tr key={patient.email} className="border-b border-[#e6e6e2]"><td className="px-5 py-4"><p className="font-semibold">{patient.name}</p><p className="text-xs text-[#434655]">{patient.profileComplete ? "Profil lengkap" : "Profil belum lengkap"}</p></td><td className="px-5 py-4 text-sm">{patient.phone || "—"}</td><td className="px-5 py-4 text-sm">{patient.email}</td><td className="px-5 py-4 text-sm">{patient.city || "—"}</td><td className="px-5 py-4"><Button variant="outline" onClick={() => navigate(`/resepsionis/data-pasien/${encodeURIComponent(patient.email)}`)}>Lihat</Button></td></tr>)}</tbody></table></div></Card></div>;
}
