import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Button, Card, Chip } from "../components/ui.jsx";
import { getReceptionistPatientHistory, getReceptionistPatientPayments, getReceptionistPatientProfile } from "../../../shared/services/receptionistPatientApi.js";

const rupiah = (value) => `Rp${Number(value || 0).toLocaleString("id-ID")}`;
function Row({ label, value }) { return <div className="flex justify-between gap-4 border-b border-[#e6e6e2] py-3 text-sm"><span className="text-[#434655]">{label}</span><span className="text-right">{value || "—"}</span></div>; }

export default function ReceptionistPatientDetailApiPage() {
  const { id } = useParams(); const email = decodeURIComponent(id); const navigate = useNavigate(); const [patient, setPatient] = useState(null); const [history, setHistory] = useState([]); const [payments, setPayments] = useState([]); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const [profile, reservationResult, paymentResult] = await Promise.all([getReceptionistPatientProfile(email), getReceptionistPatientHistory(email), getReceptionistPatientPayments(email)]); setPatient(profile); setHistory(reservationResult.data); setPayments(paymentResult); } catch (requestError) { setError(requestError.message || "Detail pasien tidak dapat dimuat."); } })(); }, [email]);
  if (error) return <Card pad="md"><p className="text-[#a03d4a]">{error}</p></Card>;
  if (!patient) return <p className="py-10 text-center text-sm">Memuat pasien…</p>;
  return <div className="flex flex-col gap-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-[28px] font-bold">Detail Pasien</h1><p className="text-sm text-[#434655]">{patient.email}</p></div><Button onClick={() => navigate(`/resepsionis/data-pasien/${encodeURIComponent(email)}/edit`)}>Edit Pasien</Button></div><div className="grid gap-5 lg:grid-cols-[280px_1fr]"><Card pad="lg"><p className="text-xl font-bold">{patient.name}</p><div className="mt-4"><Row label="Gender" value={patient.gender} /><Row label="Tanggal Lahir" value={patient.birthDate} /><Row label="Profil" value={<Chip>{patient.profileComplete ? "Lengkap" : "Belum Lengkap"}</Chip>} /></div></Card><div className="flex flex-col gap-5"><Card pad="md"><h2 className="font-bold">Informasi Pribadi</h2><div className="mt-3"><Row label="Telepon" value={patient.phone} /><Row label="Alamat" value={patient.address} /><Row label="Kota" value={patient.city} /><Row label="Pekerjaan" value={patient.job} /></div></Card><Card pad="md"><h2 className="font-bold">Riwayat Reservasi</h2><div className="mt-3 space-y-3">{history.length === 0 ? <p className="text-sm text-[#434655]">Belum ada reservasi.</p> : history.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-[#e6e6e2] pb-3"><div><p className="font-semibold">{item.service}</p><p className="text-sm text-[#434655]">{item.date} · {item.time}</p></div><div className="flex items-center gap-3"><Chip>{item.status}</Chip><Link to={`/resepsionis/reservasi/${item.id}`} className="text-sm font-semibold text-blue-600">Detail</Link></div></div>)}</div></Card><Card pad="md"><h2 className="font-bold">Riwayat Pembayaran</h2><div className="mt-3 space-y-3">{payments.length === 0 ? <p className="text-sm text-[#434655]">Belum ada pembayaran.</p> : payments.map((payment) => <div key={payment.no_reservasi} className="flex justify-between gap-3 border-b border-[#e6e6e2] pb-3"><div><p className="font-semibold">{payment.reservasi?.layanan?.nama_layanan || "Layanan"}</p><p className="text-sm text-[#434655]">{payment.metode_pembayaran}</p></div><p className="font-semibold">{rupiah(payment.total_biaya)}</p></div>)}</div></Card></div></div></div>;
}
