import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Button, Card, Field, Input, Select, Textarea } from "../components/ui.jsx";
import { createReceptionistReservation, getReceptionistPatients, getReceptionistSchedules, getReceptionistServices } from "../../../shared/services/receptionistApi.js";

const rupiah = (value) => `Rp${Number(value || 0).toLocaleString("id-ID")}`;
const today = () => new Date().toISOString().slice(0, 10);

export default function ReceptionistNewReservationApiPage() {
  const navigate = useNavigate();
  const [patients, setPatients] = useState([]); const [services, setServices] = useState([]); const [slots, setSlots] = useState([]);
  const [patient, setPatient] = useState(""); const [serviceId, setServiceId] = useState(""); const [date, setDate] = useState(""); const [slotId, setSlotId] = useState(""); const [complaint, setComplaint] = useState("");
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { (async () => { try { const [patientResult, serviceResult] = await Promise.all([getReceptionistPatients({ limit: 100 }), getReceptionistServices({ status: "Aktif", limit: 100 })]); setPatients(patientResult.data); setServices(serviceResult.data); } catch (requestError) { setError(requestError.message || "Data formulir tidak dapat dimuat."); } finally { setLoading(false); } })(); }, []);
  useEffect(() => { if (!date) { setSlots([]); return; } (async () => { try { setSlots(await getReceptionistSchedules(date)); } catch (requestError) { setError(requestError.message || "Jadwal tidak dapat dimuat."); } })(); }, [date]);
  const service = services.find((item) => String(item.id) === serviceId);
  const starts = useMemo(() => { if (!service) return []; const required = service.duration / 30; return slots.filter((slot, index) => slots.slice(index, index + required).length === required && slots.slice(index, index + required).every((item, offset) => item.status_jadwal === "Aktif" && !item.no_reservasi && (offset === 0 || new Date(`1970-01-01T${item.jam_mulai}:00Z`).getTime() - new Date(`1970-01-01T${slots[index + offset - 1].jam_mulai}:00Z`).getTime() === 1800000))); }, [slots, service]);
  const submit = async (event) => { event.preventDefault(); if (!patient || !service || !slotId) return; const startIndex = slots.findIndex((slot) => String(slot.id_jadwal) === slotId); const slotIds = slots.slice(startIndex, startIndex + service.duration / 30).map((slot) => slot.id_jadwal); setSaving(true); setError(""); try { const created = await createReceptionistReservation({ email_pasien: patient, id_layanan: service.id, id_jadwal: slotIds, keluhan_awal: complaint }); navigate(`/resepsionis/reservasi/${created.id}`); } catch (requestError) { setError(requestError.message || "Reservasi tidak dapat dibuat."); } finally { setSaving(false); } };
  return <form onSubmit={submit} className="mx-auto flex max-w-3xl flex-col gap-5"><div><Link to="/resepsionis/reservasi" className="text-sm font-semibold text-[#3d4940] hover:underline">← Kembali ke Reservasi</Link><h1 className="mt-2 text-[28px] font-bold text-[#191c1e]">Reservasi Baru</h1></div><Card pad="lg"><div className="grid gap-4 sm:grid-cols-2"><Field label="Pasien" required><Select value={patient} disabled={loading} onChange={(event) => setPatient(event.target.value)}><option value="">Pilih pasien</option>{patients.map((item) => <option key={item.email} value={item.email}>{item.name} — {item.email}</option>)}</Select></Field><Field label="Layanan" required><Select value={serviceId} disabled={loading} onChange={(event) => { setServiceId(event.target.value); setSlotId(""); }}><option value="">Pilih layanan aktif</option>{services.map((item) => <option key={item.id} value={item.id}>{item.name} ({item.duration} menit)</option>)}</Select></Field><Field label="Tanggal" required><Input type="date" min={today()} value={date} onChange={(event) => { setDate(event.target.value); setSlotId(""); }} /></Field><Field label="Jam mulai" required><Select value={slotId} disabled={!service || !date} onChange={(event) => setSlotId(event.target.value)}><option value="">Pilih jam tersedia</option>{starts.map((slot) => <option key={slot.id_jadwal} value={slot.id_jadwal}>{slot.jam_mulai} – {slot.jam_selesai}</option>)}</Select></Field><Field label="Keluhan awal" className="sm:col-span-2"><Textarea rows={4} value={complaint} onChange={(event) => setComplaint(event.target.value)} placeholder="Opsional" /></Field></div>{service && <p className="mt-4 text-sm text-[#434655]">Durasi {service.duration} menit · Total {rupiah(service.price)}</p>}{error && <p className="mt-4 rounded-lg bg-[#fdf1f1] p-3 text-sm text-[#a03d4a]">{error}</p>}</Card><div className="flex justify-end"><Button type="submit" disabled={saving || !patient || !service || !slotId}>{saving ? "Membuat Reservasi…" : "Buat Reservasi"}</Button></div></form>;
}
