import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Button, Card, Chip, Modal, Textarea } from "../components/ui.jsx";
import { getReceptionistReservationDetail, updateReceptionistReservationStatus } from "../../../shared/services/receptionistApi.js";

const rupiah = (value) => `Rp${Number(value || 0).toLocaleString("id-ID")}`;

export default function ReceptionistReservationDetailApiPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [reservation, setReservation] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [pending, setPending] = useState(null); const [reason, setReason] = useState("");
  const load = async () => { setLoading(true); try { setReservation(await getReceptionistReservationDetail(id)); } catch (requestError) { setError(requestError.message || "Reservasi tidak dapat dimuat."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [id]);
  const update = async (action) => { try { const updated = await updateReceptionistReservationStatus(id, action, action === "batal" ? { alasan_pembatalan: reason } : undefined); setReservation(updated); setPending(null); } catch (requestError) { setError(requestError.message || "Status reservasi tidak dapat diubah."); setPending(null); } };
  if (loading) return <p className="py-10 text-center text-sm text-[#434655]">Memuat reservasi…</p>;
  if (!reservation) return <Card pad="md"><p className="text-[#a03d4a]">{error || "Reservasi tidak ditemukan."}</p></Card>;
  const canAttend = reservation.status === "Terjadwal"; const canFinish = reservation.status === "Hadir";
  return <div className="flex flex-col gap-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-[28px] font-bold text-[#191c1e]">Detail Reservasi</h1><p className="mt-1 text-sm text-[#434655]">{reservation.id}</p></div><Chip>{reservation.status}</Chip></div>{error && <p className="rounded-lg bg-[#fdf1f1] p-3 text-sm text-[#a03d4a]">{error}</p>}<div className="flex flex-wrap gap-3">{canAttend && <Button onClick={() => setPending("hadir")}>Tandai Hadir</Button>}{canFinish && <Button onClick={() => setPending("selesai")}>Tandai Selesai</Button>}{canAttend && <Button variant="dangerSoft" onClick={() => setPending("batal")}>Batalkan</Button>}<Button variant="outline" onClick={() => navigate("/resepsionis/reservasi")}>Kembali</Button></div><div className="grid gap-5 lg:grid-cols-2"><Card pad="md"><h2 className="font-bold">Pasien</h2><p className="mt-3 font-semibold">{reservation.patientName}</p><p className="text-sm text-[#434655]">{reservation.patientEmail}</p><p className="text-sm text-[#434655]">{reservation.phone}</p></Card><Card pad="md"><h2 className="font-bold">Layanan dan Jadwal</h2><p className="mt-3 font-semibold">{reservation.service}</p><p className="text-sm text-[#434655]">{rupiah(reservation.price)} · {reservation.duration} menit</p><p className="mt-3 text-sm">{reservation.date} · {reservation.time} – {reservation.endTime}</p></Card><Card pad="md" className="lg:col-span-2"><h2 className="font-bold">Keluhan Awal</h2><p className="mt-3 text-sm text-[#434655]">{reservation.complaint || "Tidak ada keluhan yang dicatat."}</p></Card></div>{pending && <Modal icon={<span className="text-xl font-bold">!</span>} iconTone={pending === "batal" ? "red" : "brand"} title={pending === "batal" ? "Batalkan Reservasi" : pending === "hadir" ? "Tandai Pasien Hadir" : "Selesaikan Reservasi"} subtitle="Konfirmasi perubahan status reservasi." onClose={() => setPending(null)} footer={<><Button variant="outline" onClick={() => setPending(null)}>Batal</Button><Button variant={pending === "batal" ? "danger" : "primary"} disabled={pending === "batal" && !reason.trim()} onClick={() => update(pending)}>Konfirmasi</Button></>}>{pending === "batal" && <Textarea rows={4} value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Alasan pembatalan" />}</Modal>}</div>;
}
